### ISSUE TITLE
Too many layers

### ISSUE THREAD

**Issue by g4s8** [yegor256/rultor-image#1]
The Dockerfile contains too many layers, where some of them are redundant.
For instance just look at this line:
https://github.com/yegor256/rultor-image/blob/9f19515d924d6e29261d49994f712da94694be34/Dockerfile#L150

Docker will install all software and create new image layer of some size (let's say 1Gb, where `/tmp` dir will be 200 MB)
Then it removes `/tmp` in next `RUN` - it's creating new image layer with a diff for previous layer (new image will be 200 MB)
So the final image size is 1Gb + 200Mb = 1200Mb, instead of expecting 1Gb - 200Mb = 800Mb.

Instead of creating new image layers with `RUN` it would be better to chain commands in one `RUN`, for example:
```dockerfile
RUN apt-get update && apt-get install -y some-package && rm -rf /tmp/*
```
Here only the resulting files will be included into image layer.

Docker images are similar to git commits: if you create one huge commit and then remove some files in next commit, the `.git` directory will be bigger than size of files in first commit.

You may check how I created Rultor images for Go in this file: https://github.com/g4s8/dockers/blob/master/gorultor/Dockerfile

**Comment by yegor256** [comment]
@g4s8 I believe it's fixed already
