### ISSUE TITLE
Image is Using Java 11 instead of Java 8?

### ISSUE THREAD

**Issue by amihaiemil** [yegor256/rultor-image#5]
Running a Maven Build seems to work until the ``javadoc`` command. I get the message:
```
Error while generating Javadoc: Unable to find javadoc command:
The environment variable JAVA_HOME is not correctly
```
So apparently the ``ENV JAVA_HOME ...`` command from the Dockerfile isn't working. 

What's even more interesting, the following output shows Java 11:

```
$ whereis java
    java: /usr/bin/java /usr/share/java /usr/share/man/man1/java.1.gz
$ java --version
    openjdk 11.0.6 2020-01-14 
    OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)    
    OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)
```

**Comment by yegor256** [comment]
@amihaiemil I see that `javadoc` exists in the image out of the box. You don't need to configure anything. Just remove the line where you configure `JAVA_HOME` from your `.rultor.yml` and try again.

**Comment by amihaiemil** [comment]
@yegor256 Just tried it again, I'm still getting the error

```
Error while generating Javadoc: Unable to find javadoc command:
The environment variable JAVA_HOME is not correctly set.m -> 1m[Help 1]m
```
I'm not setting JAVA_HOME anywhere...

**Comment by yegor256** [comment]
@amihaiemil try this:

```
update-java-alternatives -s java-1.8.0-openjdk-amd64
```

Or, from Rultor:

```
sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
```
