### ISSUE TITLE
Bug when we want to use java 8

### ISSUE THREAD

**Issue by baudoliver7** [yegor256/rultor-image#9]
We get this error :
```cmd
update-java-alternatives: directory does not exist: /usr/lib/jvm/java-1.8.0-openjdk-amd64
```
when we try to execute this command in rultor :
```cmd
update-java-alternatives -s java-1.8.0-openjdk-amd64
```
We noticed that the latest versions of `Ubuntu` used in rultor image (`18.x` to `20.x`) don't have `java 8` installed by default.

The issue has been observed [here](https://github.com/yegor256/takes/pull/1094#issuecomment-952247327).

Please, update `README` file after fixing it.

**Comment by yegor256** [comment]
@baudoliver7 I will upgrade to Java 17 now

**Comment by yegor256** [comment]
@rultor release, tag is `1.9.0`

**Comment by yegor256** [comment]
@rultor release, tag is `1.9.0`

**Comment by yegor256** [comment]
@rultor release, tag is `1.9.0`

**Comment by yegor256** [comment]
@rultor release, tag is `1.9.0`

**Comment by yegor256** [comment]
@rultor release, tag is `1.9.0`

**Comment by yegor256** [comment]
@rultor release, tag is `1.9.0`

**Comment by yegor256** [comment]
@rultor release, tag is `1.9.0`

**Comment by yegor256** [comment]
@rultor release, tag is `1.9.0`

**Comment by baudoliver7** [comment]
@yegor256 Thanks for changes. You just forgot to update README file about support for java 8.

**Comment by yegor256** [comment]
@baudoliver7 maybe you can contribute?
